apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      run: frontend
  replicas: 2
  template:
    metadata:
      labels:
        run: frontend
    spec:
      containers:
      - name: frontend
        image: docker.io/abdlruhman/udagram-frontend:v3
        ports: 
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
            
  env:

         -name: aws_secrets
          valuefrom:
            secretKeyRef:
              name: mysecret


        -name: Conifg1
          valuefrom:
           configMapKeyRef:
            name: env-configmap

            -name: Secrets
              valuefrom:
                secretKeyRef:
                  name: env-secret

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    run: frontend
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: frontend