apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
spec:
  selector:
    matchLabels:
      run: reverseproxy
  replicas: 2
  template:
    metadata:
      labels:
        run: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: docker.io/abdlruhman/udagram-reverseproxy:v3
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 500m

  env:
    
        -name: POSTGRES_USERNAME
          valuefrom:
           configMapKeyRef:
            name: env-configmap
            key: POSTGRES_USERNAME

            -name: POSTGRES_PASSWORD
          valuefrom:
           configMapKeyRef:
            name: env-configmap
            key: POSTGRES_PASSWORD

               -name: POSTGRES_HOST
          valuefrom:
           configMapKeyRef:
            name: env-configmap
            key: POSTGRES_HOST

               -name: POSTGRES_DB
          valuefrom:
           configMapKeyRef:
            name: env-configmap
            key: POSTGRES_DB

              -name: AWS_BUCKET
          valuefrom:
           configMapKeyRef:
            name: env-configmap
            key: AWS_BUCKET

              -name: AWS_REGION
          valuefrom:
           configMapKeyRef:
            name: env-configmap
            key: AWS_REGION

               -name: JWT_SECRET
          valuefrom:
           configMapKeyRef:
            name: env-configmap
            key: JWT_SECRET

                 -name: URL
          valuefrom:
           configMapKeyRef:
            name: env-configmap
            key: URL


            -name: POSTGRESS_USERNAME
              valuefrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRESS_USERNAME

              -name: POSTGRESS_PASSWORD
              valuefrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRESS_PASSWORD

             -name: credentials
          valuefrom:
            secretKeyRef:
              name: credentials


---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: reverseproxy